import { scenarioDefinitionSchema } from "@brass-ledger/shared";

export const soloScenario = scenarioDefinitionSchema.parse({
  id: "brass-ledger-jhq",
  title: "Brass Ledger",
  description:
    "A single-player joint headquarters campaign about warning deterioration, reserve strain, sustainment limits, and the political cost of building credible readiness under pressure.",
  contentVersion: "0.4.0",
  maxTurns: 12,
  chiefs: [
    { id: "warden", name: "Maj. Gen. Ruth Warden", directorate: "people", title: "Chief of People", doctrineBias: "preserve deployable experience before chasing visible tempo", temperament: "plainspoken and protective", competence: 0.78, riskTolerance: 0.34, preferredTags: ["retention", "reserve", "recovery", "training"], concernTags: ["escalatory", "tempo-spike"] },
    { id: "halden", name: "Dr. Elias Halden", directorate: "intelligence", title: "Chief of Intelligence", doctrineBias: "confidence before commitment", temperament: "clinical and skeptical", competence: 0.9, riskTolerance: 0.28, preferredTags: ["collection", "warning", "counter-deception", "industrial-watch"], concernTags: ["escalatory", "public-commitment"] },
    { id: "briggs", name: "Lt. Gen. Mara Briggs", directorate: "operations", title: "Chief of Operations", doctrineBias: "readiness must be visible enough to deter", temperament: "impatient and direct", competence: 0.84, riskTolerance: 0.66, preferredTags: ["deterrence", "exercise", "forward-posture", "fires"], concernTags: ["slow-burn", "committee-heavy"] },
    { id: "okafor", name: "Lt. Gen. Tunde Okafor", directorate: "sustainment", title: "Chief of Sustainment", doctrineBias: "keep the force supportable before making it busy", temperament: "methodical and constraint-driven", competence: 0.86, riskTolerance: 0.31, preferredTags: ["repair", "munitions", "lift", "fuel"], concernTags: ["tempo-spike", "escalatory"] },
    { id: "sato", name: "Gen. Mina Sato", directorate: "plans", title: "Chief of Plans", doctrineBias: "shape the theater before it hardens against you", temperament: "strategic and political", competence: 0.82, riskTolerance: 0.48, preferredTags: ["alliance", "modernization", "program", "public-commitment"], concernTags: ["ad-hoc", "hollow"] },
    { id: "navarro", name: "Lt. Gen. Elena Navarro", directorate: "training", title: "Chief of Training", doctrineBias: "repetition before prestige", temperament: "exacting and unsentimental", competence: 0.85, riskTolerance: 0.38, preferredTags: ["training", "recovery", "simulation", "standardization"], concernTags: ["tempo-spike", "hollow"] },
  ],
  capabilityPrograms: [
    { id: "fires-network", label: "Joint Fires Network", summary: "Long-range targeting and fires integration across the theater force.", absorbingDirectorate: "operations", payoff: "Creates a credible operational deterrent once integrated and trained.", fragility: "Moves fastest on paper; stalls if training and sustainment do not keep up.", preferredTags: ["fires", "deterrence", "simulation"] },
    { id: "counter-deception-grid", label: "Counter-Deception Grid", summary: "Collection, validation, and red-team measures that improve warning reliability.", absorbingDirectorate: "intelligence", payoff: "Improves warning time and protects commander confidence.", fragility: "Looks effective early, but collapses if the brief is overclaimed.", preferredTags: ["counter-deception", "collection", "warning"] },
    { id: "sustainment-ledger", label: "Sustainment Ledger", summary: "Repair, stock, and movement transparency across depots and lift nodes.", absorbingDirectorate: "sustainment", payoff: "Reduces backlog and makes tempo more supportable.", fragility: "Slow to field and easy to oversell while depots remain overloaded.", preferredTags: ["repair", "lift", "fuel", "program"] },
    { id: "reserve-rebuild", label: "Reserve Rebuild", summary: "Retention, reserve predictability, and training recovery for the manpower base.", absorbingDirectorate: "people", payoff: "Raises deployable strength without burning the force out.", fragility: "Politically easier to announce than to sustain.", preferredTags: ["retention", "reserve", "training", "recovery"] },
  ],
  externalConstraints: [
    { id: "shipping-market", label: "Commercial Shipping Market", summary: "Available hulls and charter prices for sustainment movement." },
    { id: "electronics-chain", label: "Trusted Electronics Chain", summary: "Secure electronics supply for sensors, depot tooling, and targeting systems." },
    { id: "propellant-market", label: "Propellant Market", summary: "Availability of propellant and precursor inputs for munitions output." },
  ],
  memoTemplates: [
    {
      id: "posture",
      category: "Operational Posture",
      title: "Posture for the northern frontage",
      issue: "Probe tempo is climbing while the force is still rebuilding readiness. The room needs a posture for the next month that balances deterrence, reserve strain, and political exposure.",
      whyNow: "Adversary probing remains calibrated below open conflict, but warning time is not long enough to hide indecision.",
      sponsorDirectorate: "operations",
      objectorDirectorate: "people",
      assumptions: ["Adversary probes will continue below the threshold of open conflict.", "The reserve base can absorb one more month of visible pressure if handled carefully."],
      knownUnknowns: ["How much of the current warning picture is deception rather than real preparation.", "How quickly allied reassurance would offset the domestic cost of higher visibility."],
      optional: false,
      options: [
        { id: "measured-deterrence", label: "Measured deterrence posture", summary: "Raise visibility selectively through rehearsed readiness moves without advertising a general surge.", tradeoffs: ["Improves deterrence without the full political cost of a surge.", "May still leave operations wanting more visible mass."], burden: [{ directorate: "operations", points: 2 }, { directorate: "training", points: 1 }, { directorate: "people", points: 1 }], tags: ["deterrence", "training", "recovery"], linkedActionIds: [], assumptions: ["Warning time will remain above 36 hours."], stateDelta: { forceGeneration: { deployableUnits: 0.7, trainingThroughput: 4, reserveStrain: 3 }, domestic: { cabinetCover: -2, mediaHeat: 2 }, alliance: { reassurance: 2, politicalAlignment: 1 }, escalation: { probeTempo: 1, incidentLadder: 2 } }, programPushes: [{ programId: "reserve-rebuild", points: 9 }], constraintShifts: [] },
        { id: "quiet-recovery", label: "Quiet recovery posture", summary: "Hold visible activity inside training and recovery lanes while protecting readiness from burnout.", tradeoffs: ["Protects the force and domestic cover.", "Risks looking passive if probes continue to rise."], burden: [{ directorate: "people", points: 2 }, { directorate: "training", points: 2 }, { directorate: "operations", points: 1 }], tags: ["recovery", "retention", "training", "slow-burn"], linkedActionIds: [], assumptions: [], stateDelta: { forceGeneration: { deployableUnits: 0.4, reserveStrain: -4, trainingThroughput: 5, personnelShortfalls: -3 }, domestic: { cabinetCover: 2, mediaHeat: -1, publicPatience: 3 }, alliance: { reassurance: -1 }, escalation: { probeTempo: 1, incidentLadder: -1 } }, programPushes: [{ programId: "reserve-rebuild", points: 12 }], constraintShifts: [] },
        { id: "surge-exercises", label: "Visible exercise surge", summary: "Push high-profile exercises and forward rehearsal to show immediate resolve.", tradeoffs: ["Quickest visible deterrent effect.", "Highest reserve strain and sustainment stress."], burden: [{ directorate: "operations", points: 3 }, { directorate: "training", points: 2 }, { directorate: "sustainment", points: 2 }, { directorate: "people", points: 2 }], tags: ["exercise", "deterrence", "tempo-spike", "escalatory"], linkedActionIds: [], assumptions: [], stateDelta: { forceGeneration: { deployableUnits: 1.1, reserveStrain: 7, trainingThroughput: 2, personnelShortfalls: 2 }, domestic: { cabinetCover: -5, mediaHeat: 5, publicPatience: -2 }, alliance: { reassurance: 3, partnerParticipation: 2 }, escalation: { probeTempo: 2, incidentLadder: 5, crisisSensitivity: 3 } }, programPushes: [{ programId: "fires-network", points: 6 }], constraintShifts: [] },
      ],
    },
    {
      id: "intelligence-focus",
      category: "Intelligence Focus",
      title: "Collection and warning emphasis",
      issue: "The current picture is usable but patchy. The headquarters needs to decide whether to spend scarce bandwidth on warning, industrial intelligence, or counter-deception.",
      whyNow: "The room is making decisions off a brief that remains partly estimated rather than confirmed.",
      sponsorDirectorate: "intelligence",
      objectorDirectorate: "operations",
      assumptions: ["Collection capacity can only sustain one main effort without degrading confidence elsewhere."],
      knownUnknowns: ["Which parts of the current industrial picture are deliberate deception."],
      optional: false,
      options: [
        { id: "warning-net", label: "Frontier warning net", summary: "Weight collection and analysis toward warning reliability and shorter alert cycles.", tradeoffs: ["Improves confidence in sudden posture shifts.", "Leaves less bandwidth for industrial exploitation."], burden: [{ directorate: "intelligence", points: 3 }, { directorate: "operations", points: 1 }], tags: ["warning", "collection"], linkedActionIds: [], assumptions: [], stateDelta: { intelligence: { confidence: 5, warningReliability: 8, collectionCoverage: 2 }, escalation: { warningTime: 8, crisisSensitivity: -1 } }, programPushes: [{ programId: "counter-deception-grid", points: 8 }], constraintShifts: [] },
        { id: "industrial-watch", label: "Industrial watch", summary: "Focus collection on components, lift markets, and munitions inputs to sharpen program realism.", tradeoffs: ["Better planning and sustainment realism.", "Less immediate payoff in tactical warning."], burden: [{ directorate: "intelligence", points: 2 }, { directorate: "plans", points: 1 }, { directorate: "sustainment", points: 1 }], tags: ["industrial-watch", "program", "collection"], linkedActionIds: [], assumptions: [], stateDelta: { intelligence: { confidence: 3, collectionCoverage: 5 }, sustainment: { munitionsSufficiency: 2, liftAvailability: 2 } }, programPushes: [{ programId: "sustainment-ledger", points: 8 }, { programId: "fires-network", points: 4 }], constraintShifts: [{ constraintId: "shipping-market", delta: -4 }, { constraintId: "electronics-chain", delta: -3 }] },
        { id: "deception-hunt", label: "Counter-deception hunt", summary: "Build a sharper red-team and validation cycle to protect the brief from adversary manipulation.", tradeoffs: ["Reduces the risk of acting on a false picture.", "Consumes elite analysts and slows routine throughput."], burden: [{ directorate: "intelligence", points: 4 }, { directorate: "plans", points: 1 }], tags: ["counter-deception", "warning"], linkedActionIds: [], assumptions: [], stateDelta: { intelligence: { confidence: 7, deceptionPressure: -8, warningReliability: 4 }, domestic: { cabinetCover: 1 } }, programPushes: [{ programId: "counter-deception-grid", points: 12 }], constraintShifts: [] },
      ],
    },
    {
      id: "sustainment-focus",
      category: "Sustainment Priority",
      title: "What sustainment must protect first",
      issue: "The force can promise tempo, but depot, munitions, and lift limits mean one lane must get priority.",
      whyNow: "The current sustainment picture is not yet strong enough to support every line of effort at once.",
      sponsorDirectorate: "sustainment",
      objectorDirectorate: "operations",
      assumptions: ["Sustainment friction this month will become next month’s readiness truth."],
      knownUnknowns: ["Whether commercial movement and depot throughput will tighten at the same time."],
      optional: false,
      options: [
        { id: "repair-first", label: "Repair and depot recovery", summary: "Put effort into depot flow, spare parts, and maintenance recovery.", tradeoffs: ["Best choice for sustained readiness recovery.", "Lower immediate payoff in visible theater tempo."], burden: [{ directorate: "sustainment", points: 3 }, { directorate: "operations", points: 1 }], tags: ["repair", "recovery"], linkedActionIds: [], assumptions: [], stateDelta: { sustainment: { depotBacklog: -10, fuelSufficiency: 2 }, forceGeneration: { deployableUnits: 0.5 }, domestic: { cabinetCover: 1 } }, programPushes: [{ programId: "sustainment-ledger", points: 12 }], constraintShifts: [] },
        { id: "munitions-hedge", label: "Munitions hedge", summary: "Protect propellant and ammunition sufficiency ahead of a possible deterioration in the theater.", tradeoffs: ["Improves deterrent depth.", "Looks abstract if readiness remains visibly flat."], burden: [{ directorate: "sustainment", points: 2 }, { directorate: "plans", points: 1 }], tags: ["munitions", "fires", "program"], linkedActionIds: [], assumptions: [], stateDelta: { sustainment: { munitionsSufficiency: 8 }, escalation: { incidentLadder: -1 }, domestic: { mediaHeat: 1 } }, programPushes: [{ programId: "fires-network", points: 9 }], constraintShifts: [{ constraintId: "propellant-market", delta: -6 }] },
        { id: "lift-assurance", label: "Lift assurance package", summary: "Spend effort on movement guarantees and fuel routing so later options remain executable.", tradeoffs: ["Strengthens flexibility under surprise.", "Provides less immediately visible readiness effect."], burden: [{ directorate: "sustainment", points: 3 }, { directorate: "plans", points: 1 }], tags: ["lift", "fuel", "program"], linkedActionIds: [], assumptions: [], stateDelta: { sustainment: { liftAvailability: 8, fuelSufficiency: 6 }, alliance: { reassurance: 1 } }, programPushes: [{ programId: "sustainment-ledger", points: 8 }], constraintShifts: [{ constraintId: "shipping-market", delta: -8 }] },
      ],
    },
    {
      id: "alliance-frame",
      category: "Alliance and Political Frame",
      title: "How to frame the month to partners and cabinet",
      issue: "Alliance reassurance and domestic cover are both thin enough that the headquarters cannot communicate loosely.",
      whyNow: "Partners want steadier reassurance while cabinet tolerance is starting to narrow.",
      sponsorDirectorate: "plans",
      objectorDirectorate: "intelligence",
      assumptions: ["Public alignment and partner alignment will not always move together."],
      knownUnknowns: ["Whether partner governments will match reassuring language with actual participation."],
      optional: false,
      options: [
        { id: "quiet-reassurance", label: "Quiet reassurance", summary: "Use private partner channels and restrained public language to steady the coalition without raising the domestic temperature.", tradeoffs: ["Safest for cabinet cover.", "Less visible reassurance to operations-minded partners."], burden: [{ directorate: "plans", points: 2 }, { directorate: "intelligence", points: 1 }], tags: ["alliance", "quiet"], linkedActionIds: [], assumptions: [], stateDelta: { alliance: { reassurance: 5, politicalAlignment: 3 }, domestic: { cabinetCover: 2, mediaHeat: -2, publicPatience: 1 }, escalation: { incidentLadder: -1 } }, programPushes: [], constraintShifts: [] },
        { id: "public-assurance-tour", label: "Public assurance tour", summary: "Lean into public alliance signaling to show visible backing and resolve.", tradeoffs: ["Raises visible reassurance quickly.", "Exposes the headquarters to domestic criticism if readiness does not keep pace."], burden: [{ directorate: "plans", points: 3 }, { directorate: "operations", points: 1 }], tags: ["alliance", "public-commitment", "deterrence"], linkedActionIds: [], assumptions: [], stateDelta: { alliance: { reassurance: 8, politicalAlignment: 5, partnerParticipation: 2 }, domestic: { cabinetCover: -2, mediaHeat: 4 }, escalation: { probeTempo: 1, incidentLadder: 2 } }, programPushes: [], constraintShifts: [] },
        { id: "modernization-case", label: "Modernization case to cabinet and allies", summary: "Spend political capital making the case that force design and programs now will prevent a worse bill later.", tradeoffs: ["Accelerates long-run capability programs.", "Turns scrutiny onto every gap in the current force."], burden: [{ directorate: "plans", points: 3 }, { directorate: "sustainment", points: 1 }, { directorate: "intelligence", points: 1 }], tags: ["modernization", "program", "committee-heavy", "public-commitment"], linkedActionIds: [], assumptions: [], stateDelta: { alliance: { politicalAlignment: 4, reassurance: 3 }, domestic: { cabinetCover: -3, committeeTolerance: -2, mediaHeat: 5 } }, programPushes: [{ programId: "fires-network", points: 6 }, { programId: "sustainment-ledger", points: 6 }], constraintShifts: [] },
      ],
    },
    {
      id: "force-development",
      category: "Force Development",
      title: "Which capability line gets the month’s extra attention",
      issue: "The headquarters can advance one capability line with real intent this month, but not every line at once.",
      whyNow: "The modernization debate is starting to outpace the force’s ability to absorb new ideas cleanly.",
      sponsorDirectorate: "plans",
      objectorDirectorate: "training",
      assumptions: ["Program progress that outruns integration and training creates false confidence rather than usable advantage."],
      knownUnknowns: ["Which capability line will matter most if the theater deteriorates earlier than expected."],
      optional: true,
      options: [
        { id: "fires-prototype", label: "Accelerate the fires prototype", summary: "Push the joint fires network forward to create a future deterrent edge.", tradeoffs: ["Potentially the biggest upside in deterrence.", "Most exposed to training and sustainment absorption problems."], burden: [{ directorate: "plans", points: 1 }, { directorate: "operations", points: 2 }, { directorate: "training", points: 2 }, { directorate: "sustainment", points: 1 }], tags: ["fires", "modernization", "simulation"], linkedActionIds: [], assumptions: [], stateDelta: { forceGeneration: { trainingThroughput: -1 }, domestic: { cabinetCover: -1, mediaHeat: 2 }, escalation: { incidentLadder: 1 } }, programPushes: [{ programId: "fires-network", points: 14 }], constraintShifts: [{ constraintId: "electronics-chain", delta: 3 }, { constraintId: "propellant-market", delta: 2 }] },
        { id: "deception-grid", label: "Expand the counter-deception grid", summary: "Use the month to harden the brief rather than advertise a new kinetic edge.", tradeoffs: ["Best for clearer decision-making under fog.", "Least visible payoff to the public and some allies."], burden: [{ directorate: "intelligence", points: 2 }, { directorate: "plans", points: 1 }, { directorate: "training", points: 1 }], tags: ["counter-deception", "program", "warning"], linkedActionIds: [], assumptions: [], stateDelta: { intelligence: { confidence: 4, deceptionPressure: -6, warningReliability: 3 }, domestic: { cabinetCover: 1 } }, programPushes: [{ programId: "counter-deception-grid", points: 14 }], constraintShifts: [] },
        { id: "training-reset", label: "Training discipline reset", summary: "Spend the month converting lessons into standardization, instructors, and repeatable field practice.", tradeoffs: ["Most reliable path to usable medium-term readiness.", "Least dramatic headline in the short term."], burden: [{ directorate: "training", points: 3 }, { directorate: "people", points: 1 }, { directorate: "operations", points: 1 }], tags: ["training", "standardization", "recovery"], linkedActionIds: [], assumptions: [], stateDelta: { forceGeneration: { trainingThroughput: 6, deployableUnits: 0.4, reserveStrain: -2 }, domestic: { publicPatience: 2 } }, programPushes: [{ programId: "reserve-rebuild", points: 8 }, { programId: "fires-network", points: 6 }], constraintShifts: [] },
      ],
    },
  ],
  events: [
    { id: "shipping-jam", title: "Shipping jam", summary: "Regional congestion tightens commercial lift and stretches movement timelines.", minTurn: 2, maxTurn: 6, triggerTags: ["lift", "public-commitment"], requiredFlags: [], excludedFlags: [], setsFlags: ["shipping_jam"], clearsFlags: [], stateDelta: { sustainment: { liftAvailability: -7, depotBacklog: 4 }, escalation: { incidentLadder: 1 } }, constraintShifts: [{ constraintId: "shipping-market", delta: 12 }] },
    { id: "reserve-backlash", title: "Reserve backlash", summary: "Employers and local officials push back against how the reserve burden is being managed.", minTurn: 2, maxTurn: 8, triggerTags: ["tempo-spike", "reserve"], requiredFlags: [], excludedFlags: [], setsFlags: ["reserve_backlash"], clearsFlags: [], stateDelta: { forceGeneration: { reserveStrain: 7, personnelShortfalls: 3 }, domestic: { cabinetCover: -4, mediaHeat: 4, publicPatience: -3 } }, constraintShifts: [] },
    { id: "partner-relief", title: "Partner relief", summary: "A partner quietly expands participation after being reassured in the right channel.", minTurn: 2, maxTurn: 8, triggerTags: ["alliance", "quiet"], requiredFlags: [], excludedFlags: [], setsFlags: ["partner_relief"], clearsFlags: [], stateDelta: { alliance: { reassurance: 5, politicalAlignment: 4, partnerParticipation: 2 } }, constraintShifts: [] },
    { id: "scrutiny-cycle", title: "Scrutiny cycle", summary: "Cabinet committees begin asking whether modernization promises are outrunning present readiness.", minTurn: 3, maxTurn: 9, triggerTags: ["modernization", "public-commitment"], requiredFlags: [], excludedFlags: [], setsFlags: ["scrutiny_cycle"], clearsFlags: [], stateDelta: { domestic: { committeeTolerance: -5, mediaHeat: 5, cabinetCover: -3 } }, constraintShifts: [] },
    { id: "deception-slip", title: "Deception slip", summary: "A confident brief turns out to be built on manipulated indicators.", minTurn: 3, maxTurn: 10, triggerTags: ["escalatory"], requiredFlags: [], excludedFlags: ["counter_deception_mature"], setsFlags: ["deception_exposed"], clearsFlags: [], stateDelta: { intelligence: { confidence: -8, deceptionPressure: 7, warningReliability: -5 }, escalation: { warningTime: -6, incidentLadder: 3 } }, constraintShifts: [] },
    { id: "training-payoff", title: "Training payoff", summary: "Repeated drills start showing up as cleaner execution rather than better slides.", minTurn: 4, maxTurn: 10, triggerTags: ["training", "standardization"], requiredFlags: [], excludedFlags: [], setsFlags: ["training_payoff"], clearsFlags: [], stateDelta: { forceGeneration: { deployableUnits: 0.8, trainingThroughput: 3, reserveStrain: -2 }, domestic: { publicPatience: 2 } }, constraintShifts: [] },
  ],
  initialState: {
    turn: 1,
    maxTurns: 12,
    microCampaignLength: 6,
    seed: 20260330,
    campaignStatus: "active",
    campaignScore: 0,
    campaignOutcome: null,
    strategic: {
      forceGeneration: { deployableUnits: 5.2, reserveStrain: 46, trainingThroughput: 51, personnelShortfalls: 41 },
      intelligence: { collectionCoverage: 54, confidence: 52, warningReliability: 49, deceptionPressure: 43 },
      sustainment: { depotBacklog: 58, munitionsSufficiency: 49, fuelSufficiency: 53, liftAvailability: 47 },
      alliance: { reassurance: 48, politicalAlignment: 50, partnerParticipation: 44, partnerPublicSupport: 46 },
      domestic: { cabinetCover: 51, committeeTolerance: 54, mediaHeat: 39, publicPatience: 56 },
      escalation: { probeTempo: 43, warningTime: 38, incidentLadder: 34, crisisSensitivity: 48 },
    },
    resources: {
      budgetAuthority: 61,
      readiness: 53,
      politicalCapital: 56,
      allianceCohesion: 50,
      publicLegitimacy: 52,
      escalationPressure: 43,
    },
    forceGeneration: {
      deployableUnits: 5.2,
      reserveStrain: 46,
      trainingThroughput: 51,
      personnelShortfalls: 41,
    },
    intel: {
      collectionCoverage: 54,
      confidence: 52,
      warningReliability: 49,
      deceptionPressure: 43,
    },
    sustainment: {
      depotBacklog: 58,
      munitionsSufficiency: 49,
      fuelSufficiency: 53,
      liftAvailability: 47,
    },
    alliance: {
      reassurance: 48,
      politicalAlignment: 50,
      partnerParticipation: 44,
      partnerPublicSupport: 46,
    },
    domestic: {
      cabinetCover: 51,
      committeeTolerance: 54,
      mediaHeat: 39,
      publicPatience: 56,
    },
    escalation: {
      probeTempo: 43,
      warningTime: 38,
      incidentLadder: 34,
      crisisSensitivity: 48,
    },
    capabilityPrograms: [
      { id: "fires-network", phase: "concept", progress: 26, blockers: ["training absorption", "munitions depth"] },
      { id: "counter-deception-grid", phase: "funded", progress: 22, blockers: ["analyst bandwidth"] },
      { id: "sustainment-ledger", phase: "concept", progress: 34, blockers: ["trusted electronics", "depot burden"] },
      { id: "reserve-rebuild", phase: "funded", progress: 28, blockers: ["public patience", "training seats"] },
    ],
    externalConstraints: [
      { id: "shipping-market", severity: 56, trend: "steady" },
      { id: "electronics-chain", severity: 52, trend: "steady" },
      { id: "propellant-market", severity: 49, trend: "steady" },
    ],
    chiefTrust: { warden: 58, halden: 59, briggs: 57, okafor: 60, sato: 55, navarro: 58 },
    advisorTrust: {},
    activeEventIds: [],
    eventHistory: [],
    eventFlags: {},
    internalTech: [],
    externalTech: [],
    briefing: {
      theater: "Northern Frontier",
      monthLabel: "Month 1",
      situationSummary: "Probe tempo is rising, the reserve base is feeling the strain, and sustainment remains too brittle to support every attractive course of action at once.",
      riskPosture: "The force can absorb one sharp move this month, not three.",
      commandersIntent: "Recover credible readiness without spending political cover faster than the theater can justify.",
      operationalPicture: "Adversary probes are steady, the force is still rebuilding, and sustainment remains the binding constraint on how much the room can ask for at once.",
      decisionFocus: "Protect readiness without exhausting political cover or overcommitting support capacity.",
      openQuestions: ["Is the warning picture clean enough to support a more visible posture?", "Which sustainment weakness becomes the first real bottleneck if tempo rises?", "Can allies be reassured without provoking a domestic backlash?"],
      campaignObjectives: [
        { id: "readiness", label: "Finish the micro-campaign with 7 or more deployable brigades", metric: "deployableUnits", target: 7, direction: "gte", note: "Deterrence needs a force that looks usable, not just active." },
        { id: "alliance", label: "Keep alliance political alignment at 56 or more", metric: "politicalAlignment", target: 56, direction: "gte", note: "Partner reassurance cannot be allowed to drift while the headquarters rebuilds itself." },
        { id: "politics", label: "Keep cabinet cover at 32 or more", metric: "cabinetCover", target: 32, direction: "gte", note: "If domestic cover collapses, the theater plan stops being implementable." },
        { id: "escalation", label: "Keep the incident ladder at 58 or lower", metric: "incidentLadder", target: 58, direction: "lte", note: "The force must avoid stumbling into a crisis spiral while rebuilding credible posture." },
      ],
      budgetHeadline: "1.6B USD",
      readinessHeadline: "5 brigades deployable",
      geopoliticalSummary: "Pressure is rising, but the picture still favors a controlled recovery if the headquarters keeps its line of effort tight.",
    },
  },
});
